import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal-page";
import { CONTACT_EMAIL, SITE_NAME } from "@/lib/site";

export const metadata: Metadata = {
  title: `Terms of Service · ${SITE_NAME}`,
  description: `The terms for using ${SITE_NAME}.`,
};

// Have this page reviewed before any commercial launch.
export default function TermsPage() {
  const mail = <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>;

  return (
    <LegalPage
      title="Terms of Service"
      intro={`These terms apply to your use of ${SITE_NAME}. By creating an account or using the service, you agree to them. If you don't agree, please don't use ${SITE_NAME}.`}
    >
      <LegalSection title="The service">
        <p>
          {SITE_NAME} uses artificial intelligence to turn the notes you provide into study guides and practice exams,
          grades your answers, and tracks your progress. It is a study aid. It is not affiliated with any school,
          instructor or course.
        </p>
      </LegalSection>

      <LegalSection title="Who can use it">
        <p>
          You must be at least 13 years old to use {SITE_NAME}. If you are under the age of majority where you live,
          you need a parent or guardian&apos;s permission.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          Keep your sign-in details secure; you are responsible for activity on your account. Let us know at {mail} if
          you think someone else has accessed it.
        </p>
      </LegalSection>

      <LegalSection title="Your content">
        <ul>
          <li>
            <strong>You own your notes</strong> and the answers you write. You give us permission to store and process
            them, including sending them to our AI provider, only as needed to run the service for you. How we handle
            your data is described in our <Link href="/privacy">Privacy Policy</Link>.
          </li>
          <li>
            Only upload material you have the right to use, such as your own notes or course materials you&apos;re
            allowed to study from. Don&apos;t upload other people&apos;s confidential or personal information.
          </li>
          <li>You can delete your notes at any time, and you can ask us to delete your account.</li>
        </ul>
      </LegalSection>

      <LegalSection title="AI-generated content">
        <p>
          Study guides, questions, grades and feedback are generated by AI and <strong>can contain mistakes</strong>,
          including incorrect facts, unclear questions, or grades you disagree with. Always check important material
          against your course materials and instructor. Your real exam may cover different material than{" "}
          {SITE_NAME} predicts, and we can&apos;t guarantee any particular grade or result.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>When using {SITE_NAME}, you agree not to:</p>
        <ul>
          <li>Break the law, or upload content that is illegal, harmful, or infringes someone else&apos;s rights.</li>
          <li>Use it to cheat. Follow your school&apos;s academic integrity rules, including during actual exams.</li>
          <li>Try to get around usage limits, access other users&apos; data, or disrupt or overload the service.</li>
          <li>Scrape, copy or resell the service, or use it to build a competing product.</li>
        </ul>
        <p>We may suspend or close accounts that break these terms.</p>
      </LegalSection>

      <LegalSection title="Usage limits and availability">
        <p>
          To keep the service available for everyone, we limit how many study guides and exams each account can create
          per day, and these limits may change. {SITE_NAME} is provided free of charge. We may change, pause or stop
          any part of it, and it may sometimes be slow or unavailable.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimers and limitation of liability">
        <p>
          {SITE_NAME} is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind,
          including that it will be accurate, error-free or uninterrupted. To the fullest extent allowed by law, we are
          not liable for any indirect or consequential damages, or for any loss arising from your use of the service or
          of AI-generated content, including academic results.
        </p>
      </LegalSection>

      <LegalSection title="Ending your use">
        <p>
          You can stop using {SITE_NAME} at any time and ask us to delete your account by emailing {mail}. We may end
          or suspend your access if you break these terms.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          If we change these terms, we will update the date at the top of this page. If you keep using {SITE_NAME}{" "}
          after changes take effect, you accept the updated terms.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>Questions about these terms? Email {mail}.</p>
      </LegalSection>
    </LegalPage>
  );
}
